### PR TITLE
issue 205-Added levels to react-admin

### PR DESCRIPTION
**Pull request by felizj17**
Contributes to #205 

## What did you do?
Added Levels to react-admin
## Why did you do it?
Vue to React migration
## How have you tested it?
Ran test and interacted with routed pages
## Were docs updated if needed?

- [ ] No
- [ ] Yes
- [x] N/A

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new console logs
- [x] Fixes entire issue
- [ ] Partial fix for issue

### CODE REVIEW

**Review by ed-snodgrass — APPROVED** [review]
lgtm

**Comment by ed-snodgrass** [comment]
You have a failing test: looks like it is just a mis-named data-testid.

Also, some formatting stuff was merged to the `main` branch, it would be helpful if you merged those updates into your branch and ran the linter/prettier to get the formatting aligned.

**Comment by felizj17** [comment]
i just realized that geographies ended up in this PR.  Ill leave it in for now but if you want me to reset the branch i will

**Comment by ed-snodgrass** [comment]
> i just realized that geographies ended up in this PR. Ill leave it in for now but if you want me to reset the branch i will

I'll try to merge it and if it needs some adjusting I'll fix it.

**Comment by ed-snodgrass** [comment]
closes #205

**Pull request merged**
