### PR TITLE
Fix client unit test to pass in California

### PR DESCRIPTION
**Pull request by markstur**
* Due to timezone the expected date can be off by one
* I made it 11:30 so it will pass everywhere except some mid-Pacific islands
  (if anyone hits that, we could adjust the expected result)

Signed-off-by: Mark Sturdevant <mark.sturdevant@ibm.com>

### CODE REVIEW

**Comment by markstur** [comment]
@eis95 California timezone was returning 5/32 instead of 6/01.  Simplest fix was to change the time to work in all timezones except +13, +14.

**Comment by eis95** [comment]
Doesn't this mean the code itself still has a bug?

**Comment by upkarlidder** [comment]
@markstur, I also thinking the same as @eis95 

The only change in this PR is from `2020-06-01T05:00:00.000Z` to `2020-06-01T11:30:00.000Z` in the test spec. I am not sure what issue this fixes.

**Comment by markstur** [comment]
The input is UTC time. The output is local time. The new tests failed when I ran them in CA because it wasn't the same day in CA as in UTC. I'd expect them to pass 3 hours East.  Tests really should not pass/fail based on where they run, but I just picked a time that works for most of the planet to fix the test.

Re: bug in the client... I don't see it. Dates will be stored in UTC and displayed in local time. So what I've seen is fine.

Did you find a place in the client where the input needs to be converted to UTC?  I haven't seen that, but that isn't an issue with the tests.

**Comment by eis95** [comment]
I agree with @markstur that there isn't a bug. I apologize for the confusion. To make the test pass every time you can leave off the 'Z' and it should assume local when creating. This is why I prefer moment.js :)

```
      it('should return formatted date', () => {
        const wrapper = factory({ propsData: { date_introduced: '2020-06-01T01:00:00.000' } });
        expect(wrapper.vm.getIntroDt).toEqual('6-1-2020');
      });
```

**Comment by markstur** [comment]
@eis95 I like your suggestion.  How about you do a PR to fix the test by stripping the Z and I abandon this one?  No need to change the time, just the zone.  I'd rather you get credit for it -- if that is a thing.  (or just say so and I'll do it)

Also worth noting... @eis95 pointed out where the bug was fixed in the code. There was an off-by-one bug already fixed here: https://github.com/Call-for-Code-for-Racial-Justice/Truth-Loop/pull/131/files/a98e9ef001f36a10acabcf85e524771086b73320#r627045725

**Pull request closed without merging**
