### PR TITLE
Replace admin with react admin

### PR DESCRIPTION
**Pull request by ed-snodgrass**
## What did you do?
Moved the react-admin to replace the admin (vue) app.

## How have you tested it?
ran the tests locally. Built the admin app and make sure the following worked:
Admin UI: http://localhost:5000/
Quick check of rest endpoint: http://localhost:5000/api/v1/categories

## Were docs updated if needed?

- [ ] No
- [ /] Yes
- [ ] N/A

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [/ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ /] My code follows the style guidelines of this project
- [ /] I have performed a self-review of my own code
- [- ] I have commented my code, particularly in hard-to-understand areas
- [ /] My changes generate no new console logs
- [ /] Fixes entire issue
- [ ] Partial fix for issue

### CODE REVIEW

**Comment by markstur** [comment]
FYI -- my swagger problems were due to running the server on a different port (and/or running the UI in dev mode maybe?)

The swagger page will still work on any port.  Just the UI has a handy link to it that is hard-coded.

**Review by markstur — APPROVED** [review]
Looks good, Ed.  Thanks for getting all this done and coordinating/helping with other contributors too.

**Comment by ed-snodgrass** [comment]
@markstur I had meant to change that hard-coded link to api-docs to the `/api-docs`. Should I create an issue for that?

**Comment by markstur** [comment]
yes.  An issue is good.  Then you can either fix it or leave it for someone else to pick up.

**Pull request merged**
