### PR TITLE
Issue #104-- Change hover animation to hover over entire policy rather than just summary portion.

### PR DESCRIPTION
**Pull request by rahme-butaineh**
Fixed hover animation to hover over entire policy card on the client application rather than just the summary portion of the card.

### CODE REVIEW

**Comment by Mohamed-E** [comment]
Any idea why the DCO is failing the build due to "incorrect signoff"? I thought the "verified" tag signified that the commit was signed-off on.

**Review by markstur — DISMISSED** [review]
lgtm

**Comment by krook** [comment]
@Mohamed-E the "verified" piece is that it's from your account. The DCO is that you confirm that the specific new code is yours to contribute. Clicking the DCO details link can show you how to amend your commit. You can also do it in advance for future commits by adding `-s` to your `commit` commands.

**Review by markstur — APPROVED** [review]
Thanks!

**Comment by markstur** [comment]
@Mohamed-E this had conflicts so I merged it and then found that the significant change (the addition) was done by someone else in April while this PR had been stuck for a while. The result was nothing added but only the deletion of the summary pointer.  I wasn't comfortable choosing only that part of this older PR over the more recent one so I reverted it.

Do we need the removal of the summary pointer still or was the addition sufficient?

**Pull request merged**
