### PR TITLE
testfix Removing timezone from date_introduced in getIntroDt test to …

### PR DESCRIPTION
**Pull request by eis95**
…correct issues where test was failing in other timezones.

Signed-off-by: ed.snodgrass <snodgrass.ed@gmail.com>

### CODE REVIEW

**Comment by eis95** [comment]
@markstur I would've been 100% fine with you getting all the glory for this change. :)

**Review by markstur — COMMENTED** [review]
Isn't the Z on line 17 also a problem?  I can retest tomorrow.  Otherwise your 1 char fix looks great.  Thanks @eis95

**Comment by eis95** [comment]
@markstur , It definitely was the same issue. Thanks for pointing it out. All fixed.

**Review by markstur — APPROVED** [review]
Looks good.  Thank you

**Pull request merged**
